version: "3"

services: 
  golang:
    build: ./golang/.
    ports:
      - "8080:8080"
    expose:
      - "8080"
    # volumes:
    #   - /home/charo/workspaces/WWCode-MNL/golang-databases/:/go/workspace
    depends_on: 
      - mariadb
  # golang:
  #   image: golang:1.17.2
  #   depends_on:
  #     - mariadb

  mariadb:
    build: ./database/.
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306